### ISSUE TITLE
Change Documentation for Building

### ISSUE THREAD

**Issue by ttepatti** [Gioni06/stasis-generator#16]
Hello,

I noticed in the GitHub README for the project, the basic usage example shows the following:

`"build": "stasis-cli build -s stasis.config.json src",`
`"serve": "stasis-cli serve -s stasis.config.json src",`

When using this command, my client throws an "error: unknown option '-s''

Instead, I think it would be better if this was changed to the -c flag:

`"build": "stasis-cli build -c stasis.config.json src",`
`"serve": "stasis-cli serve -c stasis.config.json src",`

**Comment by Gioni06** [comment]
Hey @ttepatti. Thanks for pointing this out. I'll have a look at it soon!

**Comment by Gioni06** [comment]
`stasis-cli build -c stasis.config.json src` is correct

**Comment by Gioni06** [comment]
Fixed it. Closing this issue. Thanks @ttepatti!
